# Generated by Django 5.2.1 on 2025-06-03 07:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部门名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='部门代码')),
                ('description', models.TextField(blank=True, verbose_name='部门描述')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='部门经理')),
                ('manager_title', models.CharField(blank=True, max_length=100, verbose_name='经理职位')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='办公地点')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='部门电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='部门邮箱')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='部门预算')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_departm_name_cbbdb1_idx'), models.Index(fields=['code'], name='api_departm_code_dcd7e2_idx'), models.Index(fields=['status'], name='api_departm_status_0b40bb_idx')],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='api.department', verbose_name='部门引用'),
        ),
    ]
