# Generated by Django 5.2.1 on 2025-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department_employee_department_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='员工办公地点'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', '在职'), ('on_leave', '休假'), ('terminated', '离职')], default='active', max_length=20, verbose_name='员工状态'),
        ),
    ]
