# Generated by Django 5.2.1 on 2025-06-05 01:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_location_employee_notes_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='考勤日期')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='签到时间')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='签退时间')),
                ('status', models.CharField(choices=[('present', '出勤'), ('absent', '缺勤'), ('late', '迟到'), ('early_leave', '早退'), ('sick_leave', '病假'), ('personal_leave', '事假'), ('annual_leave', '年假'), ('overtime', '加班')], default='present', max_length=20, verbose_name='考勤状态')),
                ('work_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='工作时长(小时)')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='加班时长(小时)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='api_attenda_employe_c3e514_idx'), models.Index(fields=['date'], name='api_attenda_date_2082cd_idx'), models.Index(fields=['status'], name='api_attenda_status_f113d0_idx'), models.Index(fields=['created_at'], name='api_attenda_created_c12e1a_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
